export const INPUT_CHANGED = 'INPUT_CHANGED';

export const USER_TRY_TO_LOG_IN = 'USER_TRY_TO_LOG_IN';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAILED = 'USER_LOG_IN_FAILED';
export const USER_LOG_OUT = 'USER_LOG_OUT';

export const USER_TRY_TO_EDIT_ACCOUNT = 'USER_TRY_TO_EDIT_ACCOUNT';
export const USER_TRY_TO_LOAD_ACCOUNT = 'USER_TRY_TO_LOAD_ACCOUNT';
export const USER_LOAD_ACCOUNT_SUCCESS = 'USER_LOAD_ACCOUNT_SUCCESS';
export const USER_LOAD_ACCOUNT_FAILED = 'USER_LOAD_ACCOUNT_FAILED';

export const USER_TRY_TO_SAVE_ACCOUNT = 'USER_TRY_TO_SAVE_ACCOUNT';
export const USER_SAVE_ACCOUNT_SUCCESS = 'USER_SAVE_ACCOUNT_SUCCESS';
export const USER_SAVE_ACCOUNT_FAILED = 'USER_SAVE_ACCOUNT_FAILED';

export const USER_TRY_TO_DELETE_ACCOUNT = 'USER_TRY_TO_DELETE_ACCOUNT';
export const USER_DELETE_ACCOUNT_SUCCESS = 'USER_DELETE_ACCOUNT_SUCCESS';
export const USER_DELETE_ACCOUNT_FAILED = 'USER_DELETE_ACCOUNT_FAILED';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_MAIN_CONTENT_LOADING = 'GET_MAIN_CONTENT_LOADING';
export const GET_MAIN_CONTENT_SUCCESS = 'GET_MAIN_CONTENT_SUCCESS';
export const GET_MAIN_CONTENT_FAILED = 'GET_MAIN_CONTENT_FAILED';
